#!/bin/bash

# Script created by CanadianBacon
#
# This is the main start script
# Running this should start everything
#
# Usage
# ./StartPWP
# or
# ./StartPWP -s (For running in the background)
#
# This is only to be ran inside of the working directory
# Ex. PlantWateringProject

echo "Starting modules"

if [ "$1" = "-s" ]
then
  ./http.server.py &
  echo "HTTP Server Started"
  cd js/
  ./StartNodeServer &
  echo "Node.js Server Started"
  cd ../src/
  ./StartPlantService -s
  cd - 
else
  ./http.server.py &
  echo "HTTP Server Started"
  cd js/
  ./StartNodeServer &
  echo "Node.js Server Started"
  cd ../src/
  ./StartPlantService
  cd - 
fi

