#!/bin/bash

# Script created by CanadianBacon
#
# Usage
# ./StartPlantService
# or
# ./StartPlantservice -s (For running in the background)
#
# This is only to be ran inside of the working directory
# Ex. PlantWateringProject/src/
# Running it outside can cause unforseen issues, it will delete all .class files 

echo "Purging All .class Files"
rm -rf *.class
echo "Cleaned..."
echo "Compiling"
javac -classpath .:phidget22.jar PhidgetsControlHub.java
echo "Compiled Successfully"

if [ "$1" = "-s" ]
then
  java -classpath .:phidget22.jar PhidgetsControlHub </dev/null &>../log/logfile.txt &
  echo "Running, Output data being saved to log/logfile.txt"
else
  echo "Running Interactive Mode"
  java -classpath .:phidget22.jar PhidgetsControlHub
fi

