#!/bin/bash

# Script created by CanadianBacon
#
# Usage
# ./StartPlantService
# or
# ./StartPlantservice -s (For running in the background)
#
# This is only to be ran inside of the working directory
# Ex. PlantWateringProject/src/
# Running it outside can cause unforseen issues, it will delete all .class files 

if [ "$1" = "-s" ]
then
  java -jar PCH.jar </dev/null &>./logfile.txt &
  echo "Running, Output data being saved to PhidgetsControlHub/logfile.txt"
else
  echo "Running Interactive Mode"
  java -jar PCH.jar
fi
